[package]

name = "sprocketnes"
version = "0.1.0"
authors = [ "pcwalton@mimiga.net" ]

[[bin]]

name = "nes"
path = "nes.rs"

[dependencies.sdl2]

git = "https://github.com/AngryLawyer/rust-sdl2.git"

